name: dino_flutter_example
description: An example of using the dino_flutter package.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dino_flutter: 1.0.0
