name: dino_flutter_example
description: An example of using the dino_flutter package.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dino_flutter: ^1.0.0-pre.1