name: dino
repository: https://github.com/Exeteres/dino

packages:
  - packages/**

ide:
  intellij: false

scripts:
  test:
    description: Test dart packages
    run: dart run melos exec -c 1 -- "dart run full_coverage && dart run coverage:test_with_coverage"
    select-package:
      dir-exists: test
      flutter: false

command:
  bootstrap:
    usePubspecOverrides: true
