name: dino_extensions
description: A set of dino extensions providing modularity, configuration, and more.
version: 1.0.0-pre.0
repository: https://github.com/Exeteres/dino

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  dino: ^1.0.0-pre.0
dev_dependencies:
  test: ^1.21.1
  coverage: ^1.0.0
  full_coverage: 0.0.3
