name: dino_generator_example
description: An example of using the dino_generator package.
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  dino: 1.0.0-pre.0
dev_dependencies:
  build_runner: ^2.3.2
  dino_generator: ^1.0.0-pre.1