name: dino
description: A Dart dependency injection library aimed to be flexible, predictable and easy to use.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  test: ^1.21.1
  coverage: ^1.0.0
  full_coverage: 0.0.3
