builders:
  dino_builder:
    import: "package:dino_generator/builder.dart"
    builder_factories: ["dinoBuilder"]
    build_extensions: { ".dart": [".dino.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
