name: dino_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer:
  source_gen:
  build:
  code_builder:

dev_dependencies:
  dino:
  build_runner:
  build_test:
  test: ^1.21.1
  dart_style: ^2.0.3
  coverage: ^1.0.0
  full_coverage: 0.0.3
