name: dino_generator
description: A static code generator for the dino package.
version: 1.0.0-pre.0
repository: https://github.com/Exeteres/dino

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  source_gen: ^1.2.6
  build: ^2.3.1
  code_builder: ^4.3.0

dev_dependencies:
  dino: ^1.0.0-pre.0
  build_runner: ^2.3.2
  build_test: ^2.1.5
  test: ^1.21.1
  dart_style: ^2.0.3
  coverage: ^1.0.0
  full_coverage: 0.0.3
