name: dino_flutter
description: An integration of the dino package with the flutter framework.
version: 1.0.0-pre.0
repository: https://github.com/Exeteres/dino

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dino: ^1.0.0-pre.0
dev_dependencies:
  test: ^1.21.1
  coverage: ^1.0.0
