name: dino_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dino: 1.0.0

dev_dependencies:
  test: ^1.21.1
  coverage: ^1.0.0
